.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.35.0 */

dlabel __libm_qnan_f
    /* 69220 8015B620 7F810000 */ .word 0x7F810000
.size __libm_qnan_f, . - __libm_qnan_f
    /* 69224 8015B624 00000000 */ .word 0x00000000
    /* 69228 8015B628 00000000 */ .word 0x00000000
    /* 6922C 8015B62C 00000000 */ .word 0x00000000
