.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel sqrtf
    /* 2A3C0 8011C7C0 03E00008 */  jr         $ra
    /* 2A3C4 8011C7C4 46006004 */   sqrt.s    $fv0, $fa0
.size sqrtf, . - sqrtf
    /* 2A3C8 8011C7C8 00000000 */  nop
    /* 2A3CC 8011C7CC 00000000 */  nop
