.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osExceptionPreamble
    /* 29630 8011BA30 3C1A8012 */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* 29634 8011BA34 275ABA40 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* 29638 8011BA38 03400008 */  jr         $k0
    /* 2963C 8011BA3C 00000000 */   nop
.size __osExceptionPreamble, . - __osExceptionPreamble

/* Handwritten function */
glabel __osException
    /* 29640 8011BA40 3C1A8017 */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
    /* 29644 8011BA44 275A0F98 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
    /* 29648 8011BA48 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* 2964C 8011BA4C 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* 29650 8011BA50 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 29654 8011BA54 2401FFFC */  addiu      $at, $zero, -0x4
    /* 29658 8011BA58 0361D824 */  and        $k1, $k1, $at
    /* 2965C 8011BA5C 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 29660 8011BA60 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* 29664 8011BA64 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 29668 8011BA68 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* 2966C 8011BA6C AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* 29670 8011BA70 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 29674 8011BA74 03404021 */  addu       $t0, $k0, $zero
    /* 29678 8011BA78 3C1A8015 */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* 2967C 8011BA7C 8F5A76E0 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* 29680 8011BA80 DD090020 */  ld         $t1, 0x20($t0)
    /* 29684 8011BA84 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* 29688 8011BA88 DD090118 */  ld         $t1, 0x118($t0)
    /* 2968C 8011BA8C FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* 29690 8011BA90 DD090058 */  ld         $t1, 0x58($t0)
    /* 29694 8011BA94 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* 29698 8011BA98 DD090060 */  ld         $t1, 0x60($t0)
    /* 2969C 8011BA9C FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 296A0 8011BAA0 DD090068 */  ld         $t1, 0x68($t0)
    /* 296A4 8011BAA4 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* 296A8 8011BAA8 FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* 296AC 8011BAAC FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* 296B0 8011BAB0 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* 296B4 8011BAB4 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* 296B8 8011BAB8 FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* 296BC 8011BABC FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* 296C0 8011BAC0 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 296C4 8011BAC4 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* 296C8 8011BAC8 FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* 296CC 8011BACC FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* 296D0 8011BAD0 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* 296D4 8011BAD4 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* 296D8 8011BAD8 FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* 296DC 8011BADC FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* 296E0 8011BAE0 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* 296E4 8011BAE4 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* 296E8 8011BAE8 FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* 296EC 8011BAEC FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* 296F0 8011BAF0 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* 296F4 8011BAF4 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* 296F8 8011BAF8 FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* 296FC 8011BAFC FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* 29700 8011BB00 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* 29704 8011BB04 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* 29708 8011BB08 FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* 2970C 8011BB0C 00004012 */  mflo       $t0
    /* 29710 8011BB10 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* 29714 8011BB14 00004010 */  mfhi       $t0
    /* 29718 8011BB18 FF480110 */  sd         $t0, 0x110($k0) /* handwritten instruction */
    /* 2971C 8011BB1C 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 29720 8011BB20 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 29724 8011BB24 11200013 */  beqz       $t1, .L8011BB74
    /* 29728 8011BB28 00000000 */   nop
    /* 2972C 8011BB2C 3C088016 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 29730 8011BB30 25088BF0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 29734 8011BB34 8D080000 */  lw         $t0, 0x0($t0)
    /* 29738 8011BB38 2401FFFF */  addiu      $at, $zero, -0x1
    /* 2973C 8011BB3C 01015026 */  xor        $t2, $t0, $at
    /* 29740 8011BB40 314AFF00 */  andi       $t2, $t2, 0xFF00
    /* 29744 8011BB44 012A6025 */  or         $t4, $t1, $t2
    /* 29748 8011BB48 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 2974C 8011BB4C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 29750 8011BB50 03615824 */  and        $t3, $k1, $at
    /* 29754 8011BB54 016C5825 */  or         $t3, $t3, $t4
    /* 29758 8011BB58 AF4B0118 */  sw         $t3, 0x118($k0) /* handwritten instruction */
    /* 2975C 8011BB5C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 29760 8011BB60 01284824 */  and        $t1, $t1, $t0
    /* 29764 8011BB64 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 29768 8011BB68 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 2976C 8011BB6C 0361D824 */  and        $k1, $k1, $at
    /* 29770 8011BB70 0369D825 */  or         $k1, $k1, $t1
  .L8011BB74:
    /* 29774 8011BB74 3C09A430 */  lui        $t1, %hi(MI_INTR_MASK_REG)
    /* 29778 8011BB78 8D29000C */  lw         $t1, %lo(MI_INTR_MASK_REG)($t1)
    /* 2977C 8011BB7C 1120000B */  beqz       $t1, .L8011BBAC
    /* 29780 8011BB80 00000000 */   nop
    /* 29784 8011BB84 3C088016 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 29788 8011BB88 25088BF0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 2978C 8011BB8C 8D080000 */  lw         $t0, 0x0($t0)
    /* 29790 8011BB90 00084402 */  srl        $t0, $t0, 16
    /* 29794 8011BB94 2401FFFF */  addiu      $at, $zero, -0x1
    /* 29798 8011BB98 01014026 */  xor        $t0, $t0, $at
    /* 2979C 8011BB9C 3108003F */  andi       $t0, $t0, 0x3F
    /* 297A0 8011BBA0 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* 297A4 8011BBA4 010C4024 */  and        $t0, $t0, $t4
    /* 297A8 8011BBA8 01284825 */  or         $t1, $t1, $t0
  .L8011BBAC:
    /* 297AC 8011BBAC AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* 297B0 8011BBB0 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* 297B4 8011BBB4 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* 297B8 8011BBB8 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* 297BC 8011BBBC 11000014 */  beqz       $t0, .L8011BC10
    /* 297C0 8011BBC0 00000000 */   nop
    /* 297C4 8011BBC4 4448F800 */  cfc1       $t0, $31
    /* 297C8 8011BBC8 00000000 */  nop
    /* 297CC 8011BBCC AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* 297D0 8011BBD0 F7400130 */  sdc1       $fv0, 0x130($k0)
    /* 297D4 8011BBD4 F7420138 */  sdc1       $fv1, 0x138($k0)
    /* 297D8 8011BBD8 F7440140 */  sdc1       $ft0, 0x140($k0)
    /* 297DC 8011BBDC F7460148 */  sdc1       $ft1, 0x148($k0)
    /* 297E0 8011BBE0 F7480150 */  sdc1       $ft2, 0x150($k0)
    /* 297E4 8011BBE4 F74A0158 */  sdc1       $ft3, 0x158($k0)
    /* 297E8 8011BBE8 F74C0160 */  sdc1       $fa0, 0x160($k0)
    /* 297EC 8011BBEC F74E0168 */  sdc1       $fa1, 0x168($k0)
    /* 297F0 8011BBF0 F7500170 */  sdc1       $ft4, 0x170($k0)
    /* 297F4 8011BBF4 F7520178 */  sdc1       $ft5, 0x178($k0)
    /* 297F8 8011BBF8 F7540180 */  sdc1       $fs0, 0x180($k0)
    /* 297FC 8011BBFC F7560188 */  sdc1       $fs1, 0x188($k0)
    /* 29800 8011BC00 F7580190 */  sdc1       $fs2, 0x190($k0)
    /* 29804 8011BC04 F75A0198 */  sdc1       $fs3, 0x198($k0)
    /* 29808 8011BC08 F75C01A0 */  sdc1       $fs4, 0x1A0($k0)
    /* 2980C 8011BC0C F75E01A8 */  sdc1       $fs5, 0x1A8($k0)
  .L8011BC10:
    /* 29810 8011BC10 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 29814 8011BC14 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* 29818 8011BC18 24090002 */  addiu      $t1, $zero, 0x2
    /* 2981C 8011BC1C A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 29820 8011BC20 3109007C */  andi       $t1, $t0, 0x7C
    /* 29824 8011BC24 240A0024 */  addiu      $t2, $zero, 0x24
    /* 29828 8011BC28 112A00BF */  beq        $t1, $t2, .L8011BF28
    /* 2982C 8011BC2C 00000000 */   nop
    /* 29830 8011BC30 240A002C */  addiu      $t2, $zero, 0x2C
    /* 29834 8011BC34 112A0110 */  beq        $t1, $t2, handle_CpU
    /* 29838 8011BC38 00000000 */   nop
    /* 2983C 8011BC3C 240A0000 */  addiu      $t2, $zero, 0x0
    /* 29840 8011BC40 152A00D2 */  bne        $t1, $t2, .L8011BF8C
    /* 29844 8011BC44 00000000 */   nop
    /* 29848 8011BC48 03688024 */  and        $s0, $k1, $t0
  .L8011BC4C:
    /* 2984C 8011BC4C 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* 29850 8011BC50 00095302 */  srl        $t2, $t1, 12
    /* 29854 8011BC54 15400003 */  bnez       $t2, .L8011BC64
    /* 29858 8011BC58 00000000 */   nop
    /* 2985C 8011BC5C 00095202 */  srl        $t2, $t1, 8
    /* 29860 8011BC60 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L8011BC64:
    /* 29864 8011BC64 3C018016 */  lui        $at, %hi(__osIntOffTable)
    /* 29868 8011BC68 002A0821 */  addu       $at, $at, $t2
    /* 2986C 8011BC6C 902AB5D0 */  lbu        $t2, %lo(__osIntOffTable)($at)
    /* 29870 8011BC70 3C018016 */  lui        $at, %hi(__osIntTable)
    /* 29874 8011BC74 002A0821 */  addu       $at, $at, $t2
    /* 29878 8011BC78 8C2AB5F0 */  lw         $t2, %lo(__osIntTable)($at)
    /* 2987C 8011BC7C 01400008 */  jr         $t2
    /* 29880 8011BC80 00000000 */   nop
  jlabel .L8011BC84
    /* 29884 8011BC84 2401DFFF */  addiu      $at, $zero, -0x2001
    /* 29888 8011BC88 1000FFF0 */  b          .L8011BC4C
    /* 2988C 8011BC8C 02018024 */   and       $s0, $s0, $at
  jlabel .L8011BC90
    /* 29890 8011BC90 2401BFFF */  addiu      $at, $zero, -0x4001
    /* 29894 8011BC94 1000FFED */  b          .L8011BC4C
    /* 29898 8011BC98 02018024 */   and       $s0, $s0, $at
  jlabel .L8011BC9C
    /* 2989C 8011BC9C 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* 298A0 8011BCA0 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* 298A4 8011BCA4 24040018 */  addiu      $a0, $zero, 0x18
    /* 298A8 8011BCA8 0C046FEF */  jal        send_mesg
    /* 298AC 8011BCAC 00000000 */   nop
    /* 298B0 8011BCB0 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* 298B4 8011BCB4 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* 298B8 8011BCB8 1000FFE4 */  b          .L8011BC4C
    /* 298BC 8011BCBC 02018024 */   and       $s0, $s0, $at
  jlabel .L8011BCC0
    /* 298C0 8011BCC0 2401F7FF */  addiu      $at, $zero, -0x801
    /* 298C4 8011BCC4 02018024 */  and        $s0, $s0, $at
    /* 298C8 8011BCC8 3C098016 */  lui        $t1, %hi(__osHwIntTable)
    /* 298CC 8011BCCC 25298BB0 */  addiu      $t1, $t1, %lo(__osHwIntTable)
    /* 298D0 8011BCD0 21290008 */  addi       $t1, $t1, 0x8 /* handwritten instruction */
    /* 298D4 8011BCD4 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 298D8 8011BCD8 11400007 */  beqz       $t2, .L8011BCF8
    /* 298DC 8011BCDC 00000000 */   nop
    /* 298E0 8011BCE0 0140F809 */  jalr       $t2
    /* 298E4 8011BCE4 8D3D0004 */   lw        $sp, 0x4($t1)
    /* 298E8 8011BCE8 10400003 */  beqz       $v0, .L8011BCF8
    /* 298EC 8011BCEC 00000000 */   nop
    /* 298F0 8011BCF0 10000093 */  b          .L8011BF40
    /* 298F4 8011BCF4 00000000 */   nop
  .L8011BCF8:
    /* 298F8 8011BCF8 0C046FEF */  jal        send_mesg
    /* 298FC 8011BCFC 24040010 */   addiu     $a0, $zero, 0x10
    /* 29900 8011BD00 1000FFD2 */  b          .L8011BC4C
    /* 29904 8011BD04 00000000 */   nop
  jlabel .L8011BD08
    /* 29908 8011BD08 3C11A430 */  lui        $s1, %hi(MI_INTR_REG)
    /* 2990C 8011BD0C 8E310008 */  lw         $s1, %lo(MI_INTR_REG)($s1)
    /* 29910 8011BD10 3C088016 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 29914 8011BD14 25088BF0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 29918 8011BD18 8D080000 */  lw         $t0, 0x0($t0)
    /* 2991C 8011BD1C 00084402 */  srl        $t0, $t0, 16
    /* 29920 8011BD20 02288824 */  and        $s1, $s1, $t0
    /* 29924 8011BD24 32290001 */  andi       $t1, $s1, 0x1
    /* 29928 8011BD28 11200014 */  beqz       $t1, .L8011BD7C
    /* 2992C 8011BD2C 00000000 */   nop
    /* 29930 8011BD30 3231003E */  andi       $s1, $s1, 0x3E
    /* 29934 8011BD34 3C0CA404 */  lui        $t4, %hi(SP_STATUS_REG)
    /* 29938 8011BD38 8D8C0010 */  lw         $t4, %lo(SP_STATUS_REG)($t4)
    /* 2993C 8011BD3C 34098008 */  ori        $t1, $zero, 0x8008
    /* 29940 8011BD40 3C01A404 */  lui        $at, %hi(SP_STATUS_REG)
    /* 29944 8011BD44 AC290010 */  sw         $t1, %lo(SP_STATUS_REG)($at)
    /* 29948 8011BD48 318C0300 */  andi       $t4, $t4, 0x300
    /* 2994C 8011BD4C 11800007 */  beqz       $t4, .L8011BD6C
    /* 29950 8011BD50 00000000 */   nop
    /* 29954 8011BD54 0C046FEF */  jal        send_mesg
    /* 29958 8011BD58 24040020 */   addiu     $a0, $zero, 0x20
    /* 2995C 8011BD5C 12200044 */  beqz       $s1, .L8011BE70
    /* 29960 8011BD60 00000000 */   nop
    /* 29964 8011BD64 10000005 */  b          .L8011BD7C
    /* 29968 8011BD68 00000000 */   nop
  .L8011BD6C:
    /* 2996C 8011BD6C 0C046FEF */  jal        send_mesg
    /* 29970 8011BD70 24040058 */   addiu     $a0, $zero, 0x58
    /* 29974 8011BD74 1220003E */  beqz       $s1, .L8011BE70
    /* 29978 8011BD78 00000000 */   nop
  .L8011BD7C:
    /* 2997C 8011BD7C 32290008 */  andi       $t1, $s1, 0x8
    /* 29980 8011BD80 11200008 */  beqz       $t1, .L8011BDA4
    /* 29984 8011BD84 00000000 */   nop
    /* 29988 8011BD88 32310037 */  andi       $s1, $s1, 0x37
    /* 2998C 8011BD8C 3C01A440 */  lui        $at, %hi(VI_CURRENT_REG)
    /* 29990 8011BD90 AC200010 */  sw         $zero, %lo(VI_CURRENT_REG)($at)
    /* 29994 8011BD94 0C046FEF */  jal        send_mesg
    /* 29998 8011BD98 24040038 */   addiu     $a0, $zero, 0x38
    /* 2999C 8011BD9C 12200034 */  beqz       $s1, .L8011BE70
    /* 299A0 8011BDA0 00000000 */   nop
  .L8011BDA4:
    /* 299A4 8011BDA4 32290004 */  andi       $t1, $s1, 0x4
    /* 299A8 8011BDA8 11200009 */  beqz       $t1, .L8011BDD0
    /* 299AC 8011BDAC 00000000 */   nop
    /* 299B0 8011BDB0 3231003B */  andi       $s1, $s1, 0x3B
    /* 299B4 8011BDB4 24090001 */  addiu      $t1, $zero, 0x1
    /* 299B8 8011BDB8 3C01A450 */  lui        $at, %hi(AI_STATUS_REG)
    /* 299BC 8011BDBC AC29000C */  sw         $t1, %lo(AI_STATUS_REG)($at)
    /* 299C0 8011BDC0 0C046FEF */  jal        send_mesg
    /* 299C4 8011BDC4 24040030 */   addiu     $a0, $zero, 0x30
    /* 299C8 8011BDC8 12200029 */  beqz       $s1, .L8011BE70
    /* 299CC 8011BDCC 00000000 */   nop
  .L8011BDD0:
    /* 299D0 8011BDD0 32290002 */  andi       $t1, $s1, 0x2
    /* 299D4 8011BDD4 11200008 */  beqz       $t1, .L8011BDF8
    /* 299D8 8011BDD8 00000000 */   nop
    /* 299DC 8011BDDC 3231003D */  andi       $s1, $s1, 0x3D
    /* 299E0 8011BDE0 3C01A480 */  lui        $at, %hi(SI_STATUS_REG)
    /* 299E4 8011BDE4 AC200018 */  sw         $zero, %lo(SI_STATUS_REG)($at)
    /* 299E8 8011BDE8 0C046FEF */  jal        send_mesg
    /* 299EC 8011BDEC 24040028 */   addiu     $a0, $zero, 0x28
    /* 299F0 8011BDF0 1220001F */  beqz       $s1, .L8011BE70
    /* 299F4 8011BDF4 00000000 */   nop
  .L8011BDF8:
    /* 299F8 8011BDF8 32290010 */  andi       $t1, $s1, 0x10
    /* 299FC 8011BDFC 11200013 */  beqz       $t1, .L8011BE4C
    /* 29A00 8011BE00 00000000 */   nop
    /* 29A04 8011BE04 3231002F */  andi       $s1, $s1, 0x2F
    /* 29A08 8011BE08 24090002 */  addiu      $t1, $zero, 0x2
    /* 29A0C 8011BE0C 3C01A460 */  lui        $at, %hi(PI_STATUS_REG)
    /* 29A10 8011BE10 AC290010 */  sw         $t1, %lo(PI_STATUS_REG)($at)
    /* 29A14 8011BE14 3C098016 */  lui        $t1, %hi(__osPiIntTable)
    /* 29A18 8011BE18 25298BD8 */  addiu      $t1, $t1, %lo(__osPiIntTable)
    /* 29A1C 8011BE1C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 29A20 8011BE20 11400006 */  beqz       $t2, .L8011BE3C
    /* 29A24 8011BE24 00000000 */   nop
    /* 29A28 8011BE28 8D3D0004 */  lw         $sp, 0x4($t1)
    /* 29A2C 8011BE2C 0140F809 */  jalr       $t2
    /* 29A30 8011BE30 00402021 */   addu      $a0, $v0, $zero
    /* 29A34 8011BE34 14400003 */  bnez       $v0, .L8011BE44
    /* 29A38 8011BE38 00000000 */   nop
  .L8011BE3C:
    /* 29A3C 8011BE3C 0C046FEF */  jal        send_mesg
    /* 29A40 8011BE40 24040040 */   addiu     $a0, $zero, 0x40
  .L8011BE44:
    /* 29A44 8011BE44 1220000A */  beqz       $s1, .L8011BE70
    /* 29A48 8011BE48 00000000 */   nop
  .L8011BE4C:
    /* 29A4C 8011BE4C 32290020 */  andi       $t1, $s1, 0x20
    /* 29A50 8011BE50 11200007 */  beqz       $t1, .L8011BE70
    /* 29A54 8011BE54 00000000 */   nop
    /* 29A58 8011BE58 3231001F */  andi       $s1, $s1, 0x1F
    /* 29A5C 8011BE5C 24090800 */  addiu      $t1, $zero, 0x800
    /* 29A60 8011BE60 3C01A430 */  lui        $at, %hi(MI_MODE_REG)
    /* 29A64 8011BE64 AC290000 */  sw         $t1, %lo(MI_MODE_REG)($at)
    /* 29A68 8011BE68 0C046FEF */  jal        send_mesg
    /* 29A6C 8011BE6C 24040048 */   addiu     $a0, $zero, 0x48
  .L8011BE70:
    /* 29A70 8011BE70 2401FBFF */  addiu      $at, $zero, -0x401
    /* 29A74 8011BE74 1000FF75 */  b          .L8011BC4C
    /* 29A78 8011BE78 02018024 */   and       $s0, $s0, $at
  jlabel .L8011BE7C
    /* 29A7C 8011BE7C 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 29A80 8011BE80 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 29A84 8011BE84 0361D824 */  and        $k1, $k1, $at
    /* 29A88 8011BE88 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 29A8C 8011BE8C 3C098016 */  lui        $t1, %hi(__osShutdown)
    /* 29A90 8011BE90 25298BEC */  addiu      $t1, $t1, %lo(__osShutdown)
    /* 29A94 8011BE94 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 29A98 8011BE98 11400004 */  beqz       $t2, .L8011BEAC
    /* 29A9C 8011BE9C 00000000 */   nop
    /* 29AA0 8011BEA0 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 29AA4 8011BEA4 10000026 */  b          .L8011BF40
    /* 29AA8 8011BEA8 02018024 */   and       $s0, $s0, $at
  .L8011BEAC:
    /* 29AAC 8011BEAC 240A0001 */  addiu      $t2, $zero, 0x1
    /* 29AB0 8011BEB0 AD2A0000 */  sw         $t2, 0x0($t1)
    /* 29AB4 8011BEB4 0C046FEF */  jal        send_mesg
    /* 29AB8 8011BEB8 24040070 */   addiu     $a0, $zero, 0x70
    /* 29ABC 8011BEBC 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 29AC0 8011BEC0 02018024 */  and        $s0, $s0, $at
    /* 29AC4 8011BEC4 3C0A8015 */  lui        $t2, %hi(__osRunQueue)
    /* 29AC8 8011BEC8 8D4A76D8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 29ACC 8011BECC 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* 29AD0 8011BED0 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 29AD4 8011BED4 0361D824 */  and        $k1, $k1, $at
    /* 29AD8 8011BED8 10000019 */  b          .L8011BF40
    /* 29ADC 8011BEDC AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
  jlabel .L8011BEE0
    /* 29AE0 8011BEE0 2401FDFF */  addiu      $at, $zero, -0x201
    /* 29AE4 8011BEE4 01014024 */  and        $t0, $t0, $at
    /* 29AE8 8011BEE8 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 29AEC 8011BEEC 24040008 */  addiu      $a0, $zero, 0x8
    /* 29AF0 8011BEF0 0C046FEF */  jal        send_mesg
    /* 29AF4 8011BEF4 00000000 */   nop
    /* 29AF8 8011BEF8 2401FDFF */  addiu      $at, $zero, -0x201
    /* 29AFC 8011BEFC 1000FF53 */  b          .L8011BC4C
    /* 29B00 8011BF00 02018024 */   and       $s0, $s0, $at
  jlabel .L8011BF04
    /* 29B04 8011BF04 2401FEFF */  addiu      $at, $zero, -0x101
    /* 29B08 8011BF08 01014024 */  and        $t0, $t0, $at
    /* 29B0C 8011BF0C 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 29B10 8011BF10 24040000 */  addiu      $a0, $zero, 0x0
    /* 29B14 8011BF14 0C046FEF */  jal        send_mesg
    /* 29B18 8011BF18 00000000 */   nop
    /* 29B1C 8011BF1C 2401FEFF */  addiu      $at, $zero, -0x101
    /* 29B20 8011BF20 1000FF4A */  b          .L8011BC4C
    /* 29B24 8011BF24 02018024 */   and       $s0, $s0, $at
  .L8011BF28:
    /* 29B28 8011BF28 24090001 */  addiu      $t1, $zero, 0x1
    /* 29B2C 8011BF2C A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 29B30 8011BF30 0C046FEF */  jal        send_mesg
    /* 29B34 8011BF34 24040050 */   addiu     $a0, $zero, 0x50
    /* 29B38 8011BF38 10000001 */  b          .L8011BF40
    /* 29B3C 8011BF3C 00000000 */   nop
  jlabel .L8011BF40
    /* 29B40 8011BF40 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* 29B44 8011BF44 3C0A8015 */  lui        $t2, %hi(__osRunQueue)
    /* 29B48 8011BF48 8D4A76D8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 29B4C 8011BF4C 8D4B0004 */  lw         $t3, 0x4($t2)
    /* 29B50 8011BF50 012B082A */  slt        $at, $t1, $t3
    /* 29B54 8011BF54 10200007 */  beqz       $at, .L8011BF74
    /* 29B58 8011BF58 00000000 */   nop
    /* 29B5C 8011BF5C 03402821 */  addu       $a1, $k0, $zero
    /* 29B60 8011BF60 3C048015 */  lui        $a0, %hi(__osRunQueue)
    /* 29B64 8011BF64 0C04706D */  jal        __osEnqueueThread
    /* 29B68 8011BF68 248476D8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 29B6C 8011BF6C 08047083 */  j          __osDispatchThread
    /* 29B70 8011BF70 00000000 */   nop
  .L8011BF74:
    /* 29B74 8011BF74 3C098015 */  lui        $t1, %hi(__osRunQueue)
    /* 29B78 8011BF78 252976D8 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* 29B7C 8011BF7C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 29B80 8011BF80 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* 29B84 8011BF84 08047083 */  j          __osDispatchThread
    /* 29B88 8011BF88 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L8011BF8C:
    /* 29B8C 8011BF8C 3C018015 */  lui        $at, %hi(__osFaultedThread)
    /* 29B90 8011BF90 AC3A76E4 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
    /* 29B94 8011BF94 24090001 */  addiu      $t1, $zero, 0x1
    /* 29B98 8011BF98 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 29B9C 8011BF9C 24090002 */  addiu      $t1, $zero, 0x2
    /* 29BA0 8011BFA0 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 29BA4 8011BFA4 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* 29BA8 8011BFA8 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* 29BAC 8011BFAC 0C046FEF */  jal        send_mesg
    /* 29BB0 8011BFB0 24040060 */   addiu     $a0, $zero, 0x60
    /* 29BB4 8011BFB4 08047083 */  j          __osDispatchThread
    /* 29BB8 8011BFB8 00000000 */   nop
.size __osException, . - __osException

glabel send_mesg
    /* 29BBC 8011BFBC 03E09021 */  addu       $s2, $ra, $zero
    /* 29BC0 8011BFC0 3C0A8019 */  lui        $t2, %hi(__osEventStateTab)
    /* 29BC4 8011BFC4 254A8268 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* 29BC8 8011BFC8 01445021 */  addu       $t2, $t2, $a0
    /* 29BCC 8011BFCC 8D490000 */  lw         $t1, 0x0($t2)
    /* 29BD0 8011BFD0 11200027 */  beqz       $t1, .L8011C070
    /* 29BD4 8011BFD4 00000000 */   nop
    /* 29BD8 8011BFD8 8D2B0008 */  lw         $t3, 0x8($t1)
    /* 29BDC 8011BFDC 8D2C0010 */  lw         $t4, 0x10($t1)
    /* 29BE0 8011BFE0 016C082A */  slt        $at, $t3, $t4
    /* 29BE4 8011BFE4 10200022 */  beqz       $at, .L8011C070
    /* 29BE8 8011BFE8 00000000 */   nop
    /* 29BEC 8011BFEC 8D2D000C */  lw         $t5, 0xC($t1)
    /* 29BF0 8011BFF0 01AB6821 */  addu       $t5, $t5, $t3
    /* 29BF4 8011BFF4 01AC001A */  div        $zero, $t5, $t4
    /* 29BF8 8011BFF8 15800002 */  bnez       $t4, .L8011C004
    /* 29BFC 8011BFFC 00000000 */   nop
    /* 29C00 8011C000 0007000D */  break      7
  .L8011C004:
    /* 29C04 8011C004 2401FFFF */  addiu      $at, $zero, -0x1
    /* 29C08 8011C008 15810004 */  bne        $t4, $at, .L8011C01C
    /* 29C0C 8011C00C 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 29C10 8011C010 15A10002 */  bne        $t5, $at, .L8011C01C
    /* 29C14 8011C014 00000000 */   nop
    /* 29C18 8011C018 0006000D */  break      6
  .L8011C01C:
    /* 29C1C 8011C01C 00006810 */  mfhi       $t5
    /* 29C20 8011C020 8D2C0014 */  lw         $t4, 0x14($t1)
    /* 29C24 8011C024 24010004 */  addiu      $at, $zero, 0x4
    /* 29C28 8011C028 01A10018 */  mult       $t5, $at
    /* 29C2C 8011C02C 00006812 */  mflo       $t5
    /* 29C30 8011C030 018D6021 */  addu       $t4, $t4, $t5
    /* 29C34 8011C034 8D4D0004 */  lw         $t5, 0x4($t2)
    /* 29C38 8011C038 AD8D0000 */  sw         $t5, 0x0($t4)
    /* 29C3C 8011C03C 256A0001 */  addiu      $t2, $t3, 0x1
    /* 29C40 8011C040 AD2A0008 */  sw         $t2, 0x8($t1)
    /* 29C44 8011C044 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 29C48 8011C048 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 29C4C 8011C04C 11600008 */  beqz       $t3, .L8011C070
    /* 29C50 8011C050 00000000 */   nop
    /* 29C54 8011C054 0C04707F */  jal        __osPopThread
    /* 29C58 8011C058 01202021 */   addu      $a0, $t1, $zero
    /* 29C5C 8011C05C 00405021 */  addu       $t2, $v0, $zero
    /* 29C60 8011C060 01402821 */  addu       $a1, $t2, $zero
    /* 29C64 8011C064 3C048015 */  lui        $a0, %hi(__osRunQueue)
    /* 29C68 8011C068 0C04706D */  jal        __osEnqueueThread
    /* 29C6C 8011C06C 248476D8 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .L8011C070:
    /* 29C70 8011C070 02400008 */  jr         $s2
    /* 29C74 8011C074 00000000 */   nop
.size send_mesg, . - send_mesg

/* Handwritten function */
glabel handle_CpU
    /* 29C78 8011C078 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* 29C7C 8011C07C 01014824 */  and        $t1, $t0, $at
    /* 29C80 8011C080 00094F02 */  srl        $t1, $t1, 28
    /* 29C84 8011C084 240A0001 */  addiu      $t2, $zero, 0x1
    /* 29C88 8011C088 152AFFC0 */  bne        $t1, $t2, .L8011BF8C
    /* 29C8C 8011C08C 00000000 */   nop
    /* 29C90 8011C090 24090001 */  addiu      $t1, $zero, 0x1
    /* 29C94 8011C094 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* 29C98 8011C098 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 29C9C 8011C09C 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* 29CA0 8011C0A0 0361D825 */  or         $k1, $k1, $at
    /* 29CA4 8011C0A4 1000FFB3 */  b          .L8011BF74
    /* 29CA8 8011C0A8 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */
.size handle_CpU, . - handle_CpU

/* Handwritten function */
glabel __osEnqueueAndYield
    /* 29CAC 8011C0AC 3C058015 */  lui        $a1, %hi(__osRunningThread)
    /* 29CB0 8011C0B0 8CA576E0 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* 29CB4 8011C0B4 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 29CB8 8011C0B8 35080002 */  ori        $t0, $t0, 0x2
    /* 29CBC 8011C0BC ACA80118 */  sw         $t0, 0x118($a1)
    /* 29CC0 8011C0C0 FCB00098 */  sd         $s0, 0x98($a1)
    /* 29CC4 8011C0C4 FCB100A0 */  sd         $s1, 0xA0($a1)
    /* 29CC8 8011C0C8 FCB200A8 */  sd         $s2, 0xA8($a1)
    /* 29CCC 8011C0CC FCB300B0 */  sd         $s3, 0xB0($a1)
    /* 29CD0 8011C0D0 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* 29CD4 8011C0D4 FCB500C0 */  sd         $s5, 0xC0($a1)
    /* 29CD8 8011C0D8 FCB600C8 */  sd         $s6, 0xC8($a1)
    /* 29CDC 8011C0DC FCB700D0 */  sd         $s7, 0xD0($a1)
    /* 29CE0 8011C0E0 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* 29CE4 8011C0E4 FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* 29CE8 8011C0E8 FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* 29CEC 8011C0EC FCBF0100 */  sd         $ra, 0x100($a1)
    /* 29CF0 8011C0F0 ACBF011C */  sw         $ra, 0x11C($a1)
    /* 29CF4 8011C0F4 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* 29CF8 8011C0F8 1360000A */  beqz       $k1, .L8011C124 /* handwritten instruction */
    /* 29CFC 8011C0FC 00000000 */   nop
    /* 29D00 8011C100 445BF800 */  cfc1       $k1, $31
    /* 29D04 8011C104 00000000 */  nop
    /* 29D08 8011C108 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
    /* 29D0C 8011C10C F4B40180 */  sdc1       $fs0, 0x180($a1)
    /* 29D10 8011C110 F4B60188 */  sdc1       $fs1, 0x188($a1)
    /* 29D14 8011C114 F4B80190 */  sdc1       $fs2, 0x190($a1)
    /* 29D18 8011C118 F4BA0198 */  sdc1       $fs3, 0x198($a1)
    /* 29D1C 8011C11C F4BC01A0 */  sdc1       $fs4, 0x1A0($a1)
    /* 29D20 8011C120 F4BE01A8 */  sdc1       $fs5, 0x1A8($a1)
  .L8011C124:
    /* 29D24 8011C124 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* 29D28 8011C128 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 29D2C 8011C12C 1120000D */  beqz       $t1, .L8011C164
    /* 29D30 8011C130 00000000 */   nop
    /* 29D34 8011C134 3C088016 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 29D38 8011C138 25088BF0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 29D3C 8011C13C 8D080000 */  lw         $t0, 0x0($t0)
    /* 29D40 8011C140 2401FFFF */  addiu      $at, $zero, -0x1
    /* 29D44 8011C144 01014026 */  xor        $t0, $t0, $at
    /* 29D48 8011C148 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 29D4C 8011C14C 01284825 */  or         $t1, $t1, $t0
    /* 29D50 8011C150 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 29D54 8011C154 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 29D58 8011C158 0361D824 */  and        $k1, $k1, $at
    /* 29D5C 8011C15C 0369D825 */  or         $k1, $k1, $t1
    /* 29D60 8011C160 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .L8011C164:
    /* 29D64 8011C164 3C1BA430 */  lui        $k1, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
    /* 29D68 8011C168 8F7B000C */  lw         $k1, %lo(MI_INTR_MASK_REG)($k1) /* handwritten instruction */
    /* 29D6C 8011C16C 1360000B */  beqz       $k1, .L8011C19C /* handwritten instruction */
    /* 29D70 8011C170 00000000 */   nop
    /* 29D74 8011C174 3C1A8016 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* 29D78 8011C178 275A8BF0 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* 29D7C 8011C17C 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 29D80 8011C180 001AD402 */  srl        $k0, $k0, 16
    /* 29D84 8011C184 2401FFFF */  addiu      $at, $zero, -0x1
    /* 29D88 8011C188 0341D026 */  xor        $k0, $k0, $at
    /* 29D8C 8011C18C 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* 29D90 8011C190 8CA80128 */  lw         $t0, 0x128($a1)
    /* 29D94 8011C194 0348D024 */  and        $k0, $k0, $t0
    /* 29D98 8011C198 037AD825 */  or         $k1, $k1, $k0
  .L8011C19C:
    /* 29D9C 8011C19C 10800003 */  beqz       $a0, .L8011C1AC
    /* 29DA0 8011C1A0 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* 29DA4 8011C1A4 0C04706D */  jal        __osEnqueueThread
    /* 29DA8 8011C1A8 00000000 */   nop
  .L8011C1AC:
    /* 29DAC 8011C1AC 08047083 */  j          __osDispatchThread
    /* 29DB0 8011C1B0 00000000 */   nop
.size __osEnqueueAndYield, . - __osEnqueueAndYield

glabel __osEnqueueThread
    /* 29DB4 8011C1B4 0080C821 */  addu       $t9, $a0, $zero
    /* 29DB8 8011C1B8 8C980000 */  lw         $t8, 0x0($a0)
    /* 29DBC 8011C1BC 8CAF0004 */  lw         $t7, 0x4($a1)
    /* 29DC0 8011C1C0 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 29DC4 8011C1C4 01CF082A */  slt        $at, $t6, $t7
    /* 29DC8 8011C1C8 14200007 */  bnez       $at, .L8011C1E8
    /* 29DCC 8011C1CC 00000000 */   nop
  .L8011C1D0:
    /* 29DD0 8011C1D0 0300C821 */  addu       $t9, $t8, $zero
    /* 29DD4 8011C1D4 8F180000 */  lw         $t8, 0x0($t8)
    /* 29DD8 8011C1D8 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 29DDC 8011C1DC 01CF082A */  slt        $at, $t6, $t7
    /* 29DE0 8011C1E0 1020FFFB */  beqz       $at, .L8011C1D0
    /* 29DE4 8011C1E4 00000000 */   nop
  .L8011C1E8:
    /* 29DE8 8011C1E8 8F380000 */  lw         $t8, 0x0($t9)
    /* 29DEC 8011C1EC ACB80000 */  sw         $t8, 0x0($a1)
    /* 29DF0 8011C1F0 AF250000 */  sw         $a1, 0x0($t9)
    /* 29DF4 8011C1F4 03E00008 */  jr         $ra
    /* 29DF8 8011C1F8 ACA40008 */   sw        $a0, 0x8($a1)
.size __osEnqueueThread, . - __osEnqueueThread

glabel __osPopThread
    /* 29DFC 8011C1FC 8C820000 */  lw         $v0, 0x0($a0)
    /* 29E00 8011C200 8C590000 */  lw         $t9, 0x0($v0)
    /* 29E04 8011C204 03E00008 */  jr         $ra
    /* 29E08 8011C208 AC990000 */   sw        $t9, 0x0($a0)
.size __osPopThread, . - __osPopThread

/* Handwritten function */
glabel __osDispatchThread
    /* 29E0C 8011C20C 3C048015 */  lui        $a0, %hi(__osRunQueue)
    /* 29E10 8011C210 0C04707F */  jal        __osPopThread
    /* 29E14 8011C214 248476D8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 29E18 8011C218 3C018015 */  lui        $at, %hi(__osRunningThread)
    /* 29E1C 8011C21C AC2276E0 */  sw         $v0, %lo(__osRunningThread)($at)
    /* 29E20 8011C220 24080004 */  addiu      $t0, $zero, 0x4
    /* 29E24 8011C224 A4480010 */  sh         $t0, 0x10($v0)
    /* 29E28 8011C228 0040D021 */  addu       $k0, $v0, $zero
    /* 29E2C 8011C22C 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 29E30 8011C230 3C088016 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 29E34 8011C234 25088BF0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 29E38 8011C238 8D080000 */  lw         $t0, 0x0($t0)
    /* 29E3C 8011C23C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 29E40 8011C240 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 29E44 8011C244 01284824 */  and        $t1, $t1, $t0
    /* 29E48 8011C248 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 29E4C 8011C24C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 29E50 8011C250 0361D824 */  and        $k1, $k1, $at
    /* 29E54 8011C254 0369D825 */  or         $k1, $k1, $t1
    /* 29E58 8011C258 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 29E5C 8011C25C DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* 29E60 8011C260 DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* 29E64 8011C264 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* 29E68 8011C268 DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* 29E6C 8011C26C DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* 29E70 8011C270 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* 29E74 8011C274 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* 29E78 8011C278 DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* 29E7C 8011C27C DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* 29E80 8011C280 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* 29E84 8011C284 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* 29E88 8011C288 DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* 29E8C 8011C28C DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* 29E90 8011C290 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* 29E94 8011C294 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* 29E98 8011C298 DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* 29E9C 8011C29C DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* 29EA0 8011C2A0 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* 29EA4 8011C2A4 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* 29EA8 8011C2A8 DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* 29EAC 8011C2AC DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* 29EB0 8011C2B0 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* 29EB4 8011C2B4 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* 29EB8 8011C2B8 DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* 29EBC 8011C2BC DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* 29EC0 8011C2C0 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* 29EC4 8011C2C4 DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* 29EC8 8011C2C8 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* 29ECC 8011C2CC DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* 29ED0 8011C2D0 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* 29ED4 8011C2D4 03600013 */  mtlo       $k1
    /* 29ED8 8011C2D8 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* 29EDC 8011C2DC 03600011 */  mthi       $k1
    /* 29EE0 8011C2E0 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* 29EE4 8011C2E4 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* 29EE8 8011C2E8 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* 29EEC 8011C2EC 13600013 */  beqz       $k1, .L8011C33C /* handwritten instruction */
    /* 29EF0 8011C2F0 00000000 */   nop
    /* 29EF4 8011C2F4 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* 29EF8 8011C2F8 44DBF800 */  ctc1       $k1, $31
    /* 29EFC 8011C2FC D7400130 */  ldc1       $fv0, 0x130($k0)
    /* 29F00 8011C300 D7420138 */  ldc1       $fv1, 0x138($k0)
    /* 29F04 8011C304 D7440140 */  ldc1       $ft0, 0x140($k0)
    /* 29F08 8011C308 D7460148 */  ldc1       $ft1, 0x148($k0)
    /* 29F0C 8011C30C D7480150 */  ldc1       $ft2, 0x150($k0)
    /* 29F10 8011C310 D74A0158 */  ldc1       $ft3, 0x158($k0)
    /* 29F14 8011C314 D74C0160 */  ldc1       $fa0, 0x160($k0)
    /* 29F18 8011C318 D74E0168 */  ldc1       $fa1, 0x168($k0)
    /* 29F1C 8011C31C D7500170 */  ldc1       $ft4, 0x170($k0)
    /* 29F20 8011C320 D7520178 */  ldc1       $ft5, 0x178($k0)
    /* 29F24 8011C324 D7540180 */  ldc1       $fs0, 0x180($k0)
    /* 29F28 8011C328 D7560188 */  ldc1       $fs1, 0x188($k0)
    /* 29F2C 8011C32C D7580190 */  ldc1       $fs2, 0x190($k0)
    /* 29F30 8011C330 D75A0198 */  ldc1       $fs3, 0x198($k0)
    /* 29F34 8011C334 D75C01A0 */  ldc1       $fs4, 0x1A0($k0)
    /* 29F38 8011C338 D75E01A8 */  ldc1       $fs5, 0x1A8($k0)
  .L8011C33C:
    /* 29F3C 8011C33C 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* 29F40 8011C340 3C1A8016 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* 29F44 8011C344 275A8BF0 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* 29F48 8011C348 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 29F4C 8011C34C 001AD402 */  srl        $k0, $k0, 16
    /* 29F50 8011C350 037AD824 */  and        $k1, $k1, $k0
    /* 29F54 8011C354 001BD840 */  sll        $k1, $k1, 1
    /* 29F58 8011C358 3C1A8016 */  lui        $k0, %hi(__osRcpImTable) /* handwritten instruction */
    /* 29F5C 8011C35C 275AB300 */  addiu      $k0, $k0, %lo(__osRcpImTable) /* handwritten instruction */
    /* 29F60 8011C360 037AD821 */  addu       $k1, $k1, $k0
    /* 29F64 8011C364 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* 29F68 8011C368 3C1AA430 */  lui        $k0, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
    /* 29F6C 8011C36C 375A000C */  ori        $k0, $k0, %lo(MI_INTR_MASK_REG) /* handwritten instruction */
    /* 29F70 8011C370 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* 29F74 8011C374 00000000 */  nop
    /* 29F78 8011C378 00000000 */  nop
    /* 29F7C 8011C37C 00000000 */  nop
    /* 29F80 8011C380 00000000 */  nop
    /* 29F84 8011C384 42000018 */  eret /* handwritten instruction */
.size __osDispatchThread, . - __osDispatchThread

glabel __osCleanupThread
    /* 29F88 8011C388 00002021 */  addu       $a0, $zero, $zero
    /* 29F8C 8011C38C 0C04727C */  jal        osDestroyThread
    /* 29F90 8011C390 00000000 */   nop
.size __osCleanupThread, . - __osCleanupThread
    /* 29F94 8011C394 00000000 */  nop
    /* 29F98 8011C398 00000000 */  nop
    /* 29F9C 8011C39C 00000000 */  nop
