.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osGetCause
    /* 2A3D0 8011C7D0 40026800 */  mfc0       $v0, $13 /* handwritten instruction */
    /* 2A3D4 8011C7D4 03E00008 */  jr         $ra
    /* 2A3D8 8011C7D8 00000000 */   nop
.size __osGetCause, . - __osGetCause
    /* 2A3DC 8011C7DC 00000000 */  nop
