.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osGetCount
    /* 2A3E0 8011C7E0 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* 2A3E4 8011C7E4 03E00008 */  jr         $ra
    /* 2A3E8 8011C7E8 00000000 */   nop
.size osGetCount, . - osGetCount
    /* 2A3EC 8011C7EC 00000000 */  nop
