.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osGetSR
    /* 2A3F0 8011C7F0 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 2A3F4 8011C7F4 03E00008 */  jr         $ra
    /* 2A3F8 8011C7F8 00000000 */   nop
.size __osGetSR, . - __osGetSR
    /* 2A3FC 8011C7FC 00000000 */  nop
    /* 2A400 8011C800 00000000 */  nop
    /* 2A404 8011C804 00000000 */  nop
    /* 2A408 8011C808 00000000 */  nop
    /* 2A40C 8011C80C 00000000 */  nop
    /* 2A410 8011C810 00000000 */  nop
    /* 2A414 8011C814 00000000 */  nop
    /* 2A418 8011C818 00000000 */  nop
    /* 2A41C 8011C81C 00000000 */  nop
    /* 2A420 8011C820 00000000 */  nop
    /* 2A424 8011C824 00000000 */  nop
    /* 2A428 8011C828 00000000 */  nop
    /* 2A42C 8011C82C 00000000 */  nop
    /* 2A430 8011C830 00000000 */  nop
    /* 2A434 8011C834 00000000 */  nop
    /* 2A438 8011C838 00000000 */  nop
    /* 2A43C 8011C83C 00000000 */  nop
    /* 2A440 8011C840 00000000 */  nop
    /* 2A444 8011C844 00000000 */  nop
    /* 2A448 8011C848 00000000 */  nop
    /* 2A44C 8011C84C 00000000 */  nop
    /* 2A450 8011C850 00000000 */  nop
    /* 2A454 8011C854 00000000 */  nop
    /* 2A458 8011C858 00000000 */  nop
    /* 2A45C 8011C85C 00000000 */  nop
