.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osDisableInt
    /* 2A280 8011C680 3C0A8016 */  lui        $t2, %hi(__OSGlobalIntMask)
    /* 2A284 8011C684 254A8BF0 */  addiu      $t2, $t2, %lo(__OSGlobalIntMask)
    /* 2A288 8011C688 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 2A28C 8011C68C 316BFF00 */  andi       $t3, $t3, 0xFF00
    /* 2A290 8011C690 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 2A294 8011C694 2401FFFE */  addiu      $at, $zero, -0x2
    /* 2A298 8011C698 01014824 */  and        $t1, $t0, $at
    /* 2A29C 8011C69C 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 2A2A0 8011C6A0 31020001 */  andi       $v0, $t0, 0x1
    /* 2A2A4 8011C6A4 8D480000 */  lw         $t0, 0x0($t2)
    /* 2A2A8 8011C6A8 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 2A2AC 8011C6AC 110B000E */  beq        $t0, $t3, .L8011C6E8
    /* 2A2B0 8011C6B0 3C0A8015 */   lui       $t2, %hi(__osRunningThread)
    /* 2A2B4 8011C6B4 254A76E0 */  addiu      $t2, $t2, %lo(__osRunningThread)
    /* 2A2B8 8011C6B8 8D490118 */  lw         $t1, 0x118($t2)
    /* 2A2BC 8011C6BC 312AFF00 */  andi       $t2, $t1, 0xFF00
    /* 2A2C0 8011C6C0 01485024 */  and        $t2, $t2, $t0
    /* 2A2C4 8011C6C4 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 2A2C8 8011C6C8 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 2A2CC 8011C6CC 01214824 */  and        $t1, $t1, $at
    /* 2A2D0 8011C6D0 012A4825 */  or         $t1, $t1, $t2
    /* 2A2D4 8011C6D4 2401FFFE */  addiu      $at, $zero, -0x2
    /* 2A2D8 8011C6D8 01214824 */  and        $t1, $t1, $at
    /* 2A2DC 8011C6DC 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 2A2E0 8011C6E0 00000000 */  nop
    /* 2A2E4 8011C6E4 00000000 */  nop
  .L8011C6E8:
    /* 2A2E8 8011C6E8 03E00008 */  jr         $ra
    /* 2A2EC 8011C6EC 00000000 */   nop
.size __osDisableInt, . - __osDisableInt

/* Handwritten function */
glabel __osRestoreInt
    /* 2A2F0 8011C6F0 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 2A2F4 8011C6F4 01044025 */  or         $t0, $t0, $a0
    /* 2A2F8 8011C6F8 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 2A2FC 8011C6FC 00000000 */  nop
    /* 2A300 8011C700 00000000 */  nop
    /* 2A304 8011C704 03E00008 */  jr         $ra
    /* 2A308 8011C708 00000000 */   nop
.size __osRestoreInt, . - __osRestoreInt
    /* 2A30C 8011C70C 00000000 */  nop
