.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osInvalDCache
    /* 21BE0 80113FE0 18A00020 */  blez       $a1, .L80114064
    /* 21BE4 80113FE4 00000000 */   nop
    /* 21BE8 80113FE8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 21BEC 80113FEC 00AB082B */  sltu       $at, $a1, $t3
    /* 21BF0 80113FF0 1020001E */  beqz       $at, .L8011406C
    /* 21BF4 80113FF4 00000000 */   nop
    /* 21BF8 80113FF8 00804021 */  addu       $t0, $a0, $zero
    /* 21BFC 80113FFC 00854821 */  addu       $t1, $a0, $a1
    /* 21C00 80114000 0109082B */  sltu       $at, $t0, $t1
    /* 21C04 80114004 10200017 */  beqz       $at, .L80114064
    /* 21C08 80114008 00000000 */   nop
    /* 21C0C 8011400C 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 21C10 80114010 310A000F */  andi       $t2, $t0, 0xF
    /* 21C14 80114014 11400007 */  beqz       $t2, .L80114034
    /* 21C18 80114018 00000000 */   nop
    /* 21C1C 8011401C 010A4023 */  subu       $t0, $t0, $t2
    /* 21C20 80114020 BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* 21C24 80114024 0109082B */  sltu       $at, $t0, $t1
    /* 21C28 80114028 1020000E */  beqz       $at, .L80114064
    /* 21C2C 8011402C 00000000 */   nop
    /* 21C30 80114030 25080010 */  addiu      $t0, $t0, 0x10
  .L80114034:
    /* 21C34 80114034 312A000F */  andi       $t2, $t1, 0xF
    /* 21C38 80114038 11400006 */  beqz       $t2, .L80114054
    /* 21C3C 8011403C 00000000 */   nop
    /* 21C40 80114040 012A4823 */  subu       $t1, $t1, $t2
    /* 21C44 80114044 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* 21C48 80114048 0128082B */  sltu       $at, $t1, $t0
    /* 21C4C 8011404C 14200005 */  bnez       $at, .L80114064
    /* 21C50 80114050 00000000 */   nop
  .L80114054:
    /* 21C54 80114054 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* 21C58 80114058 0109082B */  sltu       $at, $t0, $t1
    /* 21C5C 8011405C 1420FFFD */  bnez       $at, .L80114054
    /* 21C60 80114060 25080010 */   addiu     $t0, $t0, 0x10
  .L80114064:
    /* 21C64 80114064 03E00008 */  jr         $ra
    /* 21C68 80114068 00000000 */   nop
  .L8011406C:
    /* 21C6C 8011406C 3C088000 */  lui        $t0, 0x8000
    /* 21C70 80114070 010B4821 */  addu       $t1, $t0, $t3
    /* 21C74 80114074 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L80114078:
    /* 21C78 80114078 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 21C7C 8011407C 0109082B */  sltu       $at, $t0, $t1
    /* 21C80 80114080 1420FFFD */  bnez       $at, .L80114078
    /* 21C84 80114084 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 21C88 80114088 03E00008 */  jr         $ra
    /* 21C8C 8011408C 00000000 */   nop
.size osInvalDCache, . - osInvalDCache
