.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osInvalICache
    /* 21C90 80114090 18A00011 */  blez       $a1, .L801140D8
    /* 21C94 80114094 00000000 */   nop
    /* 21C98 80114098 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 21C9C 8011409C 00AB082B */  sltu       $at, $a1, $t3
    /* 21CA0 801140A0 1020000F */  beqz       $at, .L801140E0
    /* 21CA4 801140A4 00000000 */   nop
    /* 21CA8 801140A8 00804021 */  addu       $t0, $a0, $zero
    /* 21CAC 801140AC 00854821 */  addu       $t1, $a0, $a1
    /* 21CB0 801140B0 0109082B */  sltu       $at, $t0, $t1
    /* 21CB4 801140B4 10200008 */  beqz       $at, .L801140D8
    /* 21CB8 801140B8 00000000 */   nop
    /* 21CBC 801140BC 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 21CC0 801140C0 310A001F */  andi       $t2, $t0, 0x1F
    /* 21CC4 801140C4 010A4023 */  subu       $t0, $t0, $t2
  .L801140C8:
    /* 21CC8 801140C8 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 21CCC 801140CC 0109082B */  sltu       $at, $t0, $t1
    /* 21CD0 801140D0 1420FFFD */  bnez       $at, .L801140C8
    /* 21CD4 801140D4 25080020 */   addiu     $t0, $t0, 0x20
  .L801140D8:
    /* 21CD8 801140D8 03E00008 */  jr         $ra
    /* 21CDC 801140DC 00000000 */   nop
  .L801140E0:
    /* 21CE0 801140E0 3C088000 */  lui        $t0, 0x8000
    /* 21CE4 801140E4 010B4821 */  addu       $t1, $t0, $t3
    /* 21CE8 801140E8 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L801140EC:
    /* 21CEC 801140EC BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 21CF0 801140F0 0109082B */  sltu       $at, $t0, $t1
    /* 21CF4 801140F4 1420FFFD */  bnez       $at, .L801140EC
    /* 21CF8 801140F8 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 21CFC 801140FC 03E00008 */  jr         $ra
    /* 21D00 80114100 00000000 */   nop
.size osInvalICache, . - osInvalICache
    /* 21D04 80114104 00000000 */  nop
    /* 21D08 80114108 00000000 */  nop
    /* 21D0C 8011410C 00000000 */  nop
