.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osMapTLBRdb
    /* 2A590 8011C990 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 2A594 8011C994 2409001F */  addiu      $t1, $zero, 0x1F
    /* 2A598 8011C998 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 2A59C 8011C99C 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* 2A5A0 8011C9A0 240A0017 */  addiu      $t2, $zero, 0x17
    /* 2A5A4 8011C9A4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* 2A5A8 8011C9A8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 2A5AC 8011C9AC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* 2A5B0 8011C9B0 00095982 */  srl        $t3, $t1, 6
    /* 2A5B4 8011C9B4 016A5825 */  or         $t3, $t3, $t2
    /* 2A5B8 8011C9B8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 2A5BC 8011C9BC 24090001 */  addiu      $t1, $zero, 0x1
    /* 2A5C0 8011C9C0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* 2A5C4 8011C9C4 00000000 */  nop
    /* 2A5C8 8011C9C8 42000002 */  tlbwi /* handwritten instruction */
    /* 2A5CC 8011C9CC 00000000 */  nop
    /* 2A5D0 8011C9D0 00000000 */  nop
    /* 2A5D4 8011C9D4 00000000 */  nop
    /* 2A5D8 8011C9D8 00000000 */  nop
    /* 2A5DC 8011C9DC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 2A5E0 8011C9E0 03E00008 */  jr         $ra
    /* 2A5E4 8011C9E4 00000000 */   nop
.size osMapTLBRdb, . - osMapTLBRdb
    /* 2A5E8 8011C9E8 00000000 */  nop
    /* 2A5EC 8011C9EC 00000000 */  nop
