.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osProbeTLB
    /* 2A460 8011C860 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 2A464 8011C864 310900FF */  andi       $t1, $t0, 0xFF
    /* 2A468 8011C868 2401E000 */  addiu      $at, $zero, -0x2000
    /* 2A46C 8011C86C 00815024 */  and        $t2, $a0, $at
    /* 2A470 8011C870 012A4825 */  or         $t1, $t1, $t2
    /* 2A474 8011C874 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 2A478 8011C878 00000000 */  nop
    /* 2A47C 8011C87C 00000000 */  nop
    /* 2A480 8011C880 00000000 */  nop
    /* 2A484 8011C884 42000008 */  tlbp /* handwritten instruction */
    /* 2A488 8011C888 00000000 */  nop
    /* 2A48C 8011C88C 00000000 */  nop
    /* 2A490 8011C890 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* 2A494 8011C894 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 2A498 8011C898 01615824 */  and        $t3, $t3, $at
    /* 2A49C 8011C89C 1560001A */  bnez       $t3, .L8011C908
    /* 2A4A0 8011C8A0 00000000 */   nop
    /* 2A4A4 8011C8A4 42000001 */  tlbr /* handwritten instruction */
    /* 2A4A8 8011C8A8 00000000 */  nop
    /* 2A4AC 8011C8AC 00000000 */  nop
    /* 2A4B0 8011C8B0 00000000 */  nop
    /* 2A4B4 8011C8B4 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* 2A4B8 8011C8B8 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* 2A4BC 8011C8BC 000B5842 */  srl        $t3, $t3, 1
    /* 2A4C0 8011C8C0 01646024 */  and        $t4, $t3, $a0
    /* 2A4C4 8011C8C4 15800004 */  bnez       $t4, .L8011C8D8
    /* 2A4C8 8011C8C8 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* 2A4CC 8011C8CC 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* 2A4D0 8011C8D0 10000002 */  b          .L8011C8DC
    /* 2A4D4 8011C8D4 00000000 */   nop
  .L8011C8D8:
    /* 2A4D8 8011C8D8 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L8011C8DC:
    /* 2A4DC 8011C8DC 304D0002 */  andi       $t5, $v0, 0x2
    /* 2A4E0 8011C8E0 11A00009 */  beqz       $t5, .L8011C908
    /* 2A4E4 8011C8E4 00000000 */   nop
    /* 2A4E8 8011C8E8 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* 2A4EC 8011C8EC 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* 2A4F0 8011C8F0 00411024 */  and        $v0, $v0, $at
    /* 2A4F4 8011C8F4 00021180 */  sll        $v0, $v0, 6
    /* 2A4F8 8011C8F8 008B6824 */  and        $t5, $a0, $t3
    /* 2A4FC 8011C8FC 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* 2A500 8011C900 10000002 */  b          .L8011C90C
    /* 2A504 8011C904 00000000 */   nop
  .L8011C908:
    /* 2A508 8011C908 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8011C90C:
    /* 2A50C 8011C90C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 2A510 8011C910 03E00008 */  jr         $ra
    /* 2A514 8011C914 00000000 */   nop
.size __osProbeTLB, . - __osProbeTLB
    /* 2A518 8011C918 00000000 */  nop
    /* 2A51C 8011C91C 00000000 */  nop
