.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osSetCompare
    /* 2E410 80120810 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* 2E414 80120814 03E00008 */  jr         $ra
    /* 2E418 80120818 00000000 */   nop
.size __osSetCompare, . - __osSetCompare
    /* 2E41C 8012081C 00000000 */  nop
