.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel __osSetFpcCsr
    /* 2A520 8011C920 4442F800 */  cfc1       $v0, $31
    /* 2A524 8011C924 44C4F800 */  ctc1       $a0, $31
    /* 2A528 8011C928 03E00008 */  jr         $ra
    /* 2A52C 8011C92C 00000000 */   nop
.size __osSetFpcCsr, . - __osSetFpcCsr
