.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osSetIntMask
    /* 21D10 80114110 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
    /* 21D14 80114114 3182FF01 */  andi       $v0, $t4, 0xFF01
    /* 21D18 80114118 3C088016 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 21D1C 8011411C 25088BF0 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 21D20 80114120 8D0B0000 */  lw         $t3, 0x0($t0)
    /* 21D24 80114124 2401FFFF */  addiu      $at, $zero, -0x1
    /* 21D28 80114128 01614026 */  xor        $t0, $t3, $at
    /* 21D2C 8011412C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 21D30 80114130 00481025 */  or         $v0, $v0, $t0
    /* 21D34 80114134 3C0AA430 */  lui        $t2, %hi(MI_INTR_MASK_REG)
    /* 21D38 80114138 8D4A000C */  lw         $t2, %lo(MI_INTR_MASK_REG)($t2)
    /* 21D3C 8011413C 11400005 */  beqz       $t2, .L80114154
    /* 21D40 80114140 000B4C02 */   srl       $t1, $t3, 16
    /* 21D44 80114144 2401FFFF */  addiu      $at, $zero, -0x1
    /* 21D48 80114148 01214826 */  xor        $t1, $t1, $at
    /* 21D4C 8011414C 3129003F */  andi       $t1, $t1, 0x3F
    /* 21D50 80114150 01495025 */  or         $t2, $t2, $t1
  .L80114154:
    /* 21D54 80114154 000A5400 */  sll        $t2, $t2, 16
    /* 21D58 80114158 004A1025 */  or         $v0, $v0, $t2
    /* 21D5C 8011415C 3C01003F */  lui        $at, (0x3F0000 >> 16)
    /* 21D60 80114160 00814024 */  and        $t0, $a0, $at
    /* 21D64 80114164 010B4024 */  and        $t0, $t0, $t3
    /* 21D68 80114168 000843C2 */  srl        $t0, $t0, 15
    /* 21D6C 8011416C 3C0A8016 */  lui        $t2, %hi(__osRcpImTable)
    /* 21D70 80114170 01485021 */  addu       $t2, $t2, $t0
    /* 21D74 80114174 954AB300 */  lhu        $t2, %lo(__osRcpImTable)($t2)
    /* 21D78 80114178 3C01A430 */  lui        $at, %hi(MI_INTR_MASK_REG)
    /* 21D7C 8011417C AC2A000C */  sw         $t2, %lo(MI_INTR_MASK_REG)($at)
    /* 21D80 80114180 3088FF01 */  andi       $t0, $a0, 0xFF01
    /* 21D84 80114184 3169FF00 */  andi       $t1, $t3, 0xFF00
    /* 21D88 80114188 01094024 */  and        $t0, $t0, $t1
    /* 21D8C 8011418C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 21D90 80114190 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 21D94 80114194 01816024 */  and        $t4, $t4, $at
    /* 21D98 80114198 01886025 */  or         $t4, $t4, $t0
    /* 21D9C 8011419C 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
    /* 21DA0 801141A0 00000000 */  nop
    /* 21DA4 801141A4 00000000 */  nop
    /* 21DA8 801141A8 03E00008 */  jr         $ra
    /* 21DAC 801141AC 00000000 */   nop
.size osSetIntMask, . - osSetIntMask
