.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel __osSetSR
    /* 2A530 8011C930 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* 2A534 8011C934 00000000 */  nop
    /* 2A538 8011C938 03E00008 */  jr         $ra
    /* 2A53C 8011C93C 00000000 */   nop
.size __osSetSR, . - __osSetSR
