.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osUnmapTLBAll
    /* 2A540 8011C940 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 2A544 8011C944 2409001E */  addiu      $t1, $zero, 0x1E
    /* 2A548 8011C948 3C0A8000 */  lui        $t2, (0x80000000 >> 16)
    /* 2A54C 8011C94C 408A5000 */  mtc0       $t2, $10 /* handwritten instruction */
    /* 2A550 8011C950 40801000 */  mtc0       $zero, $2 /* handwritten instruction */
    /* 2A554 8011C954 40801800 */  mtc0       $zero, $3 /* handwritten instruction */
  .L8011C958:
    /* 2A558 8011C958 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 2A55C 8011C95C 00000000 */  nop
    /* 2A560 8011C960 42000002 */  tlbwi /* handwritten instruction */
    /* 2A564 8011C964 00000000 */  nop
    /* 2A568 8011C968 00000000 */  nop
    /* 2A56C 8011C96C 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 2A570 8011C970 0521FFF9 */  bgez       $t1, .L8011C958
    /* 2A574 8011C974 00000000 */   nop
    /* 2A578 8011C978 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 2A57C 8011C97C 03E00008 */  jr         $ra
    /* 2A580 8011C980 00000000 */   nop
.size osUnmapTLBAll, . - osUnmapTLBAll
    /* 2A584 8011C984 00000000 */  nop
    /* 2A588 8011C988 00000000 */  nop
    /* 2A58C 8011C98C 00000000 */  nop
