.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osWritebackDCache
    /* 21DB0 801141B0 18A00011 */  blez       $a1, .L801141F8
    /* 21DB4 801141B4 00000000 */   nop
    /* 21DB8 801141B8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 21DBC 801141BC 00AB082B */  sltu       $at, $a1, $t3
    /* 21DC0 801141C0 1020000F */  beqz       $at, .L80114200
    /* 21DC4 801141C4 00000000 */   nop
    /* 21DC8 801141C8 00804021 */  addu       $t0, $a0, $zero
    /* 21DCC 801141CC 00854821 */  addu       $t1, $a0, $a1
    /* 21DD0 801141D0 0109082B */  sltu       $at, $t0, $t1
    /* 21DD4 801141D4 10200008 */  beqz       $at, .L801141F8
    /* 21DD8 801141D8 00000000 */   nop
    /* 21DDC 801141DC 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 21DE0 801141E0 310A000F */  andi       $t2, $t0, 0xF
    /* 21DE4 801141E4 010A4023 */  subu       $t0, $t0, $t2
  .L801141E8:
    /* 21DE8 801141E8 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 21DEC 801141EC 0109082B */  sltu       $at, $t0, $t1
    /* 21DF0 801141F0 1420FFFD */  bnez       $at, .L801141E8
    /* 21DF4 801141F4 25080010 */   addiu     $t0, $t0, 0x10
  .L801141F8:
    /* 21DF8 801141F8 03E00008 */  jr         $ra
    /* 21DFC 801141FC 00000000 */   nop
  .L80114200:
    /* 21E00 80114200 3C088000 */  lui        $t0, 0x8000
    /* 21E04 80114204 010B4821 */  addu       $t1, $t0, $t3
    /* 21E08 80114208 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L8011420C:
    /* 21E0C 8011420C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 21E10 80114210 0109082B */  sltu       $at, $t0, $t1
    /* 21E14 80114214 1420FFFD */  bnez       $at, .L8011420C
    /* 21E18 80114218 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 21E1C 8011421C 03E00008 */  jr         $ra
    /* 21E20 80114220 00000000 */   nop
.size osWritebackDCache, . - osWritebackDCache
    /* 21E24 80114224 00000000 */  nop
    /* 21E28 80114228 00000000 */  nop
    /* 21E2C 8011422C 00000000 */  nop
