.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osWritebackDCacheAll
    /* 21E30 80114230 3C088000 */  lui        $t0, 0x8000
    /* 21E34 80114234 240A2000 */  addiu      $t2, $zero, 0x2000
    /* 21E38 80114238 010A4821 */  addu       $t1, $t0, $t2
    /* 21E3C 8011423C 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L80114240:
    /* 21E40 80114240 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 21E44 80114244 0109082B */  sltu       $at, $t0, $t1
    /* 21E48 80114248 1420FFFD */  bnez       $at, .L80114240
    /* 21E4C 8011424C 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 21E50 80114250 03E00008 */  jr         $ra
    /* 21E54 80114254 00000000 */   nop
.size osWritebackDCacheAll, . - osWritebackDCacheAll
    /* 21E58 80114258 00000000 */  nop
    /* 21E5C 8011425C 00000000 */  nop
