.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel bzero
    /* 24690 80116A90 00041823 */  negu       $v1, $a0
    /* 24694 80116A94 28A1000C */  slti       $at, $a1, 0xC
    /* 24698 80116A98 1420001D */  bnez       $at, .L80116B10
    /* 2469C 80116A9C 00000000 */   nop
    /* 246A0 80116AA0 30630003 */  andi       $v1, $v1, 0x3
    /* 246A4 80116AA4 10600003 */  beqz       $v1, .L80116AB4
    /* 246A8 80116AA8 00A32823 */   subu      $a1, $a1, $v1
    /* 246AC 80116AAC A8800000 */  swl        $zero, 0x0($a0)
    /* 246B0 80116AB0 00832021 */  addu       $a0, $a0, $v1
  .L80116AB4:
    /* 246B4 80116AB4 2401FFE0 */  addiu      $at, $zero, -0x20
    /* 246B8 80116AB8 00A13824 */  and        $a3, $a1, $at
    /* 246BC 80116ABC 10E0000C */  beqz       $a3, .L80116AF0
    /* 246C0 80116AC0 00A72823 */   subu      $a1, $a1, $a3
    /* 246C4 80116AC4 00E43821 */  addu       $a3, $a3, $a0
  .L80116AC8:
    /* 246C8 80116AC8 AC800000 */  sw         $zero, 0x0($a0)
    /* 246CC 80116ACC AC800004 */  sw         $zero, 0x4($a0)
    /* 246D0 80116AD0 AC800008 */  sw         $zero, 0x8($a0)
    /* 246D4 80116AD4 AC80000C */  sw         $zero, 0xC($a0)
    /* 246D8 80116AD8 24840020 */  addiu      $a0, $a0, 0x20
    /* 246DC 80116ADC AC80FFF0 */  sw         $zero, -0x10($a0)
    /* 246E0 80116AE0 AC80FFF4 */  sw         $zero, -0xC($a0)
    /* 246E4 80116AE4 AC80FFF8 */  sw         $zero, -0x8($a0)
    /* 246E8 80116AE8 1487FFF7 */  bne        $a0, $a3, .L80116AC8
    /* 246EC 80116AEC AC80FFFC */   sw        $zero, -0x4($a0)
  .L80116AF0:
    /* 246F0 80116AF0 2401FFFC */  addiu      $at, $zero, -0x4
    /* 246F4 80116AF4 00A13824 */  and        $a3, $a1, $at
    /* 246F8 80116AF8 10E00005 */  beqz       $a3, .L80116B10
    /* 246FC 80116AFC 00A72823 */   subu      $a1, $a1, $a3
    /* 24700 80116B00 00E43821 */  addu       $a3, $a3, $a0
  .L80116B04:
    /* 24704 80116B04 24840004 */  addiu      $a0, $a0, 0x4
    /* 24708 80116B08 1487FFFE */  bne        $a0, $a3, .L80116B04
    /* 2470C 80116B0C AC80FFFC */   sw        $zero, -0x4($a0)
  .L80116B10:
    /* 24710 80116B10 18A00005 */  blez       $a1, .L80116B28
    /* 24714 80116B14 00000000 */   nop
    /* 24718 80116B18 00A42821 */  addu       $a1, $a1, $a0
  .L80116B1C:
    /* 2471C 80116B1C 24840001 */  addiu      $a0, $a0, 0x1
    /* 24720 80116B20 1485FFFE */  bne        $a0, $a1, .L80116B1C
    /* 24724 80116B24 A080FFFF */   sb        $zero, -0x1($a0)
  .L80116B28:
    /* 24728 80116B28 03E00008 */  jr         $ra
    /* 2472C 80116B2C 00000000 */   nop
.size bzero, . - bzero
